### PR TITLE
Feature/basemap selector

### PR DESCRIPTION
**Pull request by tsubik**
## Overview

image

Basemap selector to switch between styled map and satellite basemap.

**[Story link](https://www.pivotaltracker.com/story/show/153173395)**

Couple other things have been fixed here:

1. Occasional BAD_REQUESTs to cartoDB while fetching tiles on Species Map
image
2. Removed extraneous requests to cartoDB. It tried to get tiles twice on first render. 
3. Not properly removed event listeners: `this.map.off('zoomend', this.setMapParams.bind(this))`

### Checklist

- [x] PR has a name that won't get you publicly shamed for vagueness
- [x] PR has a description that explains it
- [x] PR includes information for people to test it [e.g.: run `npm install`]
- [x] PR is not 2k commits long... please. :pray:

### CODE REVIEW

**Comment by simaob** [comment]
Cool, works well for me. I'm going to ask for Juan Carlos to have a look as we might need to change the colours of the polygons when with the Satellite Basemap as otherwise they are not very visible:

@juancarlosalonso can we have your thoughts on this, screenshot for information and review:

screen shot 2017-12-06 at 17 05 28

**Comment by tsubik** [comment]
Hmm, I also see now that population boundaries do not work on the satellite view :/.

**Comment by simaob** [comment]
There's a story on Pivotal to fix some issues with the Populations boundaries, maybe it's related with the way they are rendered and can be fixed together?

**Comment by tsubik** [comment]
:+1: I'm taking that story as the next one.

**Comment by simaob** [comment]
Talking with @juancarlosalonso on Slack it seems that we have `mix-blend-mode` css property as `multiply` on the countries layer, and that needs light backgrounds. So maybe when changing to satellite basemap we could disable that on the layer?

**Comment by tsubik** [comment]
Yeah, I will experiment with that. Also fixing some population boundaries issues in this branch.

**Comment by tsubik** [comment]
Maybe, changing that mix-blend-mode + showing borders?
image

**Comment by simaob** [comment]
I like the idea of the boundaries being displayed. But it still feels a bit light. @juancarlosalonso what do you think?

**Comment by tsubik** [comment]
I've updated couple things here and I also edited PR overview. I decided to not translate `Satellite` and `Map` in the selector as I would need to make separate control with React context. I think that would be overkill. I also added selected view to url to have it selected after refresh.

**Comment by simaob** [comment]
Thanks for this, Tomasz. As the overlay is not an exact copy of the actual country boundaries I am wondering if we could enable the boundaries on the satellite basemap itself, otherwise I'm sure we're going to get comments about the mismatch between the boundaries and the actual geometries. But other than that is looking good! =) And as people can always revert back to the custom map, it might be fine that the layer is a bit light.

**Comment by tsubik** [comment]
There will always be a mismatch between the boundaries and the geometries layers. We could look for a more accurate dataset with country boundaries. Hmm, maybe it would be better to get the feedback first and iterate on that. The eventual optimization of population boundaries I would like to do in the next PR so I'm taking off WIP label.

**Pull request merged**
