### PR TITLE
Feature/cosmetic changes

### PR DESCRIPTION
**Pull request by utilitymonster**
This includes:

1. Include link to birdlife factsheets for sites show page's header - [story](https://www.pivotaltracker.com/story/show/146602729)
2. Include link to birdlife factsheet on species page's header - [story](https://www.pivotaltracker.com/story/show/146602653)
3. Update styles of "Back to species" link on Look Alike Pages. - [story](https://www.pivotaltracker.com/story/show/146603031)

It also includes the previous test pages that I built but didn't get included in the last PR.

### CODE REVIEW

**Comment by simaob** [comment]
Hey Matt, I think I might be doing something wrong but I ran `npm test` and I get failed tests. Is that how I run them?

**Comment by simaob** [comment]
FYI, here's what I see on the terminal (including output from `npm install`:

screen shot 2017-06-07 at 09 26 39

**Comment by simaob** [comment]
On the upside the features seem to be working well =D but I'll wait to learn how to run the tests to merge. Tks!

**Comment by utilitymonster** [comment]
Well, glad to hear it's working at least!

Tests run well on my machine. It looks like you're missing a dependency.
Did you npm install? It's also possible that I have something  installed
globally on my machine that allows me to run the tests. I tried to do so at
the beginning because I didn't know whether you guys were going to run
them, and I wanted to minimize dependencies in the build.

**Comment by simaob** [comment]
Hey Matt, I ran npm install, but it still didn't work. Maybe I need to install a dependency that provides this: react-dom/lib/ReactTestUtils. I'd be happy to have it added to the dependencies if that's what we need.

**Comment by simaob** [comment]
Made it work by removing my `node_modules` directory and running  `npm install` afterwards. =) All tests are green.

**Pull request merged**
